
package modulos;

/**
 *
 * @author aleja
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btregresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btconsultas = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btingresos = new javax.swing.JButton();
        btreportes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btregresar.setText("Salir");
        btregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobro.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 130));

        btconsultas.setText("Consultas");
        btconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btconsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Menú del Sistema");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 130, 140));

        btingresos.setText("Ingresos");
        btingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btingresosActionPerformed(evt);
            }
        });
        getContentPane().add(btingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        btreportes.setText("Reportes");
        btreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreportesActionPerformed(evt);
            }
        });
        getContentPane().add(btreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 120, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fon.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreportesActionPerformed
        // TODO add your handling code here:
        reporte open =new reporte();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btreportesActionPerformed

    private void btconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconsultasActionPerformed
        // TODO add your handling code here:
        consulta open = new consulta();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btconsultasActionPerformed

    private void btregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregresarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btregresarActionPerformed

    private void btingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btingresosActionPerformed
        // TODO add your handling code here:
        ingresar open = new ingresar();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btingresosActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btconsultas;
    private javax.swing.JButton btingresos;
    private javax.swing.JButton btregresar;
    private javax.swing.JButton btreportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
